spring:
  jpa:
    hibernate:
      ddl-auto: update
    #show-sql: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.1.1.174:3306/my_spider?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    username: root
    password: 123456
#log配置
logging:
  file: jerryWebSpider.log
  root: info
  level.com.hytchare.jerrywebspider: DEBUG
  level.org.springframework.web: INFO
  level.org.hibernate: ERROR
#Tuwan地址
tuwan:
  #tuwan爬虫入口
  welfareUrl: https://api.tuwan.com/apps/Welfare/detail
  #图包存储路径
  #imageStorePath: /home/jerrySpider/tuwan
  imageStorePath: D:\data\tuWan
  spiderTaskName: tuwanSpiderTask
  downloadTaskName: tuwanDownloadTask
#Leshe地址
leshe:
  #leshe爬虫入口
  welfareUrl: http://111.231.221.217:34567/A:/
  #leshe待爬取相册大类，以英文逗号分隔
  collectionName: 喵写真,少女秩序,风之领域,轻兰映画,森罗财团
  imageStorePath: /home/jerrySpider/leshe
  #imageStorePath: D:\data\leshe
  spiderTaskName: lesheSpiderTask
  downloadTaskName: lesheDownloadTask
#服务端口
server:
  port: 8088
